-- V43: Add chat_session_id to assistant_conversation for browser-session-based
-- conversation grouping. Replaces the day-based grouping with explicit session
-- identifiers generated by the frontend widget.
ALTER TABLE assistant_conversation ADD COLUMN chat_session_id VARCHAR(64) NULL;

CREATE INDEX idx_assistant_conv_session
    ON assistant_conversation (chat_session_id)
    WHERE chat_session_id IS NOT NULL;
